"""Search assistance is a bounded rules-only *preview*, not active AI inference."""

from django.test import Client, TestCase

from .models import Job, JobOutbox, Membership, MembershipAudit, User, WorkspaceInvitation
from .search_assistance import search_assistance_preview
from .services import create_workspace


class OfflineSearchAssistanceTests(TestCase):
    def setUp(self):
        self.owner = User.objects.create_user(username="assist-owner")
        self.member = User.objects.create_user(username="assist-member")
        self.viewer = User.objects.create_user(username="assist-viewer")
        self.foreign_owner = User.objects.create_user(username="assist-foreign")
        self.workspace = create_workspace(
            self.owner, {"name": "Private preview", "timezone": "UTC"}
        )
        self.foreign = create_workspace(
            self.foreign_owner, {"name": "Foreign preview marker", "timezone": "UTC"}
        )
        Membership.objects.create(workspace=self.workspace, user=self.member, role="member")
        Membership.objects.create(workspace=self.workspace, user=self.viewer, role="viewer")
        self.path = f"/workspaces/{self.workspace.id}/search-assistance/"
        self.client = Client(enforce_csrf_checks=True)

    def request_preview(self, intent, actor=None):
        self.client.force_login(actor or self.owner)
        self.assertEqual(self.client.get(self.path).status_code, 200)
        return self.client.post(
            self.path,
            {
                "csrfmiddlewaretoken": self.client.cookies["csrftoken"].value,
                "intent": intent,
            },
        )

    def test_bounded_preview_from_explicit_terms_no_mutations_or_provider_claims(self):
        response = self.request_preview("Find US spas and salons in Canada.")
        self.assertEqual(response.status_code, 200)
        self.assertIn("no-store", response["Cache-Control"])
        self.assertContains(response, "Suggested configuration")
        self.assertContains(response, "CA, US")
        self.assertContains(response, "salon, spa")
        self.assertContains(response, "Not generated by a model.")
        self.assertContains(response, "phone")
        self.assertContains(response, "25")
        self.assertNotContains(response, "Find US spas and salons in Canada.")
        self.assertNotContains(response, "Foreign preview marker")
        self.assertEqual(Job.objects.count(), 0)
        self.assertEqual(JobOutbox.objects.count(), 0)
        self.assertEqual(MembershipAudit.objects.count(), 0)
        self.assertEqual(WorkspaceInvitation.objects.count(), 0)
        self.assertEqual(Membership.objects.count(), 4)

    def test_unrecognized_ambiguous_or_incomplete_scope_stays_unapplied(self):
        for intent in (
            "Find quantum photonics vendors.",
            "Find spas near the mountains.",
            "US quantum photonics vendors.",
        ):
            response = self.request_preview(intent, actor=self.member)
            self.assertEqual(response.status_code, 200)
            self.assertContains(response, "Insufficient recognized scope")
            self.assertNotContains(response, "Suggested configuration")
        self.assertFalse(Job.objects.exists())

    def test_model_not_invoked_and_output_schema_is_bounded(self):
        plan = search_assistance_preview(
            "USA spas, salons, car dealers, plumbers and insurance agents"
        )
        self.assertEqual(plan["mode"], "rules_only_no_model")
        self.assertFalse(plan["model_invoked"])
        self.assertTrue(plan["needs_user_review"])
        self.assertEqual(plan["status"], "ready_for_manual_review")
        self.assertEqual(plan["search"]["countries"], ["US"])
        self.assertEqual(
            plan["search"]["categories"],
            ["car dealer", "insurance agency", "plumber", "salon", "spa"],
        )
        self.assertEqual(plan["search"]["statuses"], [])
        self.assertEqual(plan["search"]["source_codes"], [])
        self.assertEqual(plan["search"]["required_fields"], ["phone"])
        self.assertEqual(plan["search"]["result_limit"], 25)
        self.assertFalse(Job.objects.exists())

    def test_read_role_tenant_revocation_and_anonymous_boundaries(self):
        self.assertEqual(self.client.get(self.path).status_code, 302)
        self.client.force_login(self.viewer)
        self.assertEqual(self.client.get(self.path).status_code, 403)
        self.client.force_login(self.foreign_owner)
        self.assertEqual(self.client.get(self.path).status_code, 404)
        self.assertEqual(
            self.client.get(
                f"/workspaces/{self.foreign.id}/search-assistance/"
            ).status_code,
            200,
        )
        self.client.force_login(self.member)
        self.assertEqual(self.client.get(self.path).status_code, 200)
        Membership.objects.filter(workspace=self.workspace, user=self.member).delete()
        self.assertEqual(self.client.get(self.path).status_code, 404)
        self.assertFalse(Job.objects.exists())

    def test_csrf_unsupported_fields_and_read_only_http_methods(self):
        self.client.force_login(self.owner)
        self.assertEqual(self.client.post(self.path, {"intent": "Canada salons"}).status_code, 403)
        self.client.get(self.path)
        csrf = self.client.cookies["csrftoken"].value
        self.assertEqual(
            self.client.post(
                self.path,
                {"csrfmiddlewaretoken": csrf, "intent": "Canada salons", "execute": "yes"},
            ).status_code,
            400,
        )
        self.assertEqual(self.client.get(self.path + "?intent=Canada").status_code, 400)
        self.assertEqual(
            self.client.put(
                self.path,
                {},
                content_type="application/json",
                HTTP_X_CSRFTOKEN=csrf,
            ).status_code,
            405,
        )
        self.assertFalse(Job.objects.exists())

    def test_bounded_input_refuses_private_contact_and_never_reflects_it(self):
        examples = [
            "Canada spas contact test@example.com",
            "Find US salons at +971 55 813 4857",
            "Visit https://example.com for US salons",
            "US salons" + "x" * 300,
            "bad control \x00 Canada salons",
        ]
        for intent in examples:
            response = self.request_preview(intent)
            self.assertEqual(response.status_code, 400)
            self.assertNotIn(intent, response.content.decode())
            self.assertContains(response, "without links, phone numbers")
        self.assertFalse(Job.objects.exists())

    def test_untrusted_markup_is_never_reflected_and_does_not_expand_scope(self):
        response = self.request_preview("US salons <script>alert('go')</script>")
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Suggested configuration")
        self.assertNotContains(response, "<script>")
        self.assertNotContains(response, "&lt;script&gt;")
        self.assertFalse(Job.objects.exists())
