# Generated by Django 5.2.18 on 2026-10-07 21:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_loginbucket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.workspace')),
                ('active', models.BooleanField(default=False)),
                ('lead_limit', models.PositiveIntegerField(default=0)),
                ('job_limit', models.PositiveIntegerField(default=0)),
                ('provider_call_limit', models.PositiveIntegerField(default=0)),
                ('export_limit', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.workspace')),
                ('leads', models.PositiveIntegerField(default=0)),
                ('jobs', models.PositiveIntegerField(default=0)),
                ('provider_calls', models.PositiveIntegerField(default=0)),
                ('exports', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UsageReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('leads', models.PositiveIntegerField(default=0)),
                ('jobs', models.PositiveIntegerField(default=0)),
                ('provider_calls', models.PositiveIntegerField(default=0)),
                ('exports', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='reserved', max_length=8)),
                ('settlement', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'status'], name='saas_reservation_workspace')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'key'), name='saas_reservation_key'), models.CheckConstraint(condition=models.Q(('status__in', ['reserved', 'settled', 'released'])), name='saas_reservation_status')],
            },
        ),
    ]
