# Generated by Django 5.2.18 on 2026-10-07 21:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_entitlement_usagecounter_usagereservation"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourcePolicy",
            fields=[
                ("code", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("enabled", models.BooleanField(default=False)),
                ("free_collection", models.BooleanField(default=False)),
                ("countries", models.JSONField(default=list)),
                ("categories", models.JSONField(default=list)),
                ("statuses", models.JSONField(default=list)),
                ("fields", models.JSONField(default=list)),
                ("evidence", models.JSONField(default=dict)),
                ("controls", models.JSONField(default=dict)),
                ("max_provider_calls", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="JobOutbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("submitted_revision", models.PositiveIntegerField()),
                ("source_snapshot", models.JSONField()),
                ("status", models.CharField(default="pending", max_length=9)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.job"
                    ),
                ),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="core.usagereservation"
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["pending", "cancelled"])),
                        name="saas_outbox_status",
                    )
                ],
            },
        ),
    ]
