# Generated by Django 5.2.18 on 2026-10-07 21:39

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_sourcepolicy_joboutbox"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("job_revision", models.PositiveIntegerField()),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("status", models.CharField(default="leased", max_length=9)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "outbox",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="core.joboutbox",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("outbox", "number"), name="saas_attempt_number"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "leased")),
                        fields=("outbox",),
                        name="saas_one_active_attempt",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["leased", "expired", "cancelled"])),
                        name="saas_attempt_status",
                    ),
                ],
            },
        ),
    ]
