# Generated by Django 5.2.18 on 2026-10-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_jobattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="joboutbox",
            name="expires_at",
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
