# Generated by Django 5.2.18 on 2026-10-07 22:35

import uuid

import django.db.models.deletion
from django.db import migrations, models


def protect_uncertain_rollback(apps, schema_editor):
    alias = schema_editor.connection.alias
    if (
        apps.get_model("core", "DispatchOperation").objects.using(alias).exists()
        or apps.get_model("core", "JobOutbox")
        .objects.using(alias)
        .filter(status="started")
        .exists()
        or apps.get_model("core", "JobAttempt")
        .objects.using(alias)
        .filter(status="started")
        .exists()
    ):
        raise RuntimeError(
            "Dispatch evidence exists; destructive rollback requires an explicit reconciliation/migration plan."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_joboutbox_expires_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="DispatchOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_code", models.CharField(max_length=64)),
                ("provider_key", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("request_hash", models.CharField(max_length=64)),
                ("policy_version", models.PositiveIntegerField()),
                ("policy_fingerprint", models.CharField(max_length=64)),
                ("status", models.CharField(default="started", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("unknown_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="jobattempt",
            name="saas_attempt_status",
        ),
        migrations.RemoveConstraint(
            model_name="joboutbox",
            name="saas_outbox_status",
        ),
        migrations.AddConstraint(
            model_name="jobattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["leased", "expired", "cancelled", "started"])),
                name="saas_attempt_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="joboutbox",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["pending", "cancelled", "started"])),
                name="saas_outbox_status",
            ),
        ),
        migrations.AddField(
            model_name="dispatchoperation",
            name="attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.jobattempt"
            ),
        ),
        migrations.AddField(
            model_name="dispatchoperation",
            name="job",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.job"),
        ),
        migrations.AddField(
            model_name="dispatchoperation",
            name="outbox",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operations",
                to="core.joboutbox",
            ),
        ),
        migrations.AddField(
            model_name="dispatchoperation",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.workspace"
            ),
        ),
        migrations.AddConstraint(
            model_name="dispatchoperation",
            constraint=models.UniqueConstraint(
                fields=("outbox", "source_code"), name="saas_dispatch_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="dispatchoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["started", "unknown"])),
                name="saas_dispatch_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="dispatchoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(("policy_version__gte", 1)), name="saas_dispatch_policy_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="dispatchoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "started"), ("unknown_at__isnull", True)),
                    models.Q(("status", "unknown"), ("unknown_at__isnull", False)),
                    _connector="OR",
                ),
                name="saas_dispatch_unknown_time",
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, protect_uncertain_rollback),
    ]
