# Generated by Django 5.2.18 on 2026-10-07 22:59

import django.db.models.deletion
from django.db import migrations, models


def protect_receipt_rollback(apps, schema_editor):
    alias = schema_editor.connection.alias
    if (
        apps.get_model("core", "DispatchReceipt").objects.using(alias).exists()
        or apps.get_model("core", "DispatchOperation")
        .objects.using(alias)
        .filter(call_limit__gt=0)
        .exists()
        or apps.get_model("core", "DispatchOperation")
        .objects.using(alias)
        .filter(status__in=["success", "noeffect"])
        .exists()
        or apps.get_model("core", "JobOutbox").objects.using(alias).filter(status="done").exists()
        or apps.get_model("core", "JobAttempt").objects.using(alias).filter(status="done").exists()
    ):
        raise RuntimeError(
            "Terminal receipt evidence exists; destructive rollback requires a reconciliation/migration plan."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_dispatch_write_ahead"),
    ]

    operations = [
        migrations.CreateModel(
            name="DispatchReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_code", models.CharField(max_length=64)),
                ("receipt_ref", models.CharField(max_length=96)),
                ("key_id", models.CharField(max_length=64)),
                ("body_hash", models.CharField(max_length=64)),
                ("outcome", models.CharField(max_length=8)),
                ("provider_calls", models.PositiveIntegerField()),
                ("issued_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="dispatchoperation",
            name="saas_dispatch_status",
        ),
        migrations.RemoveConstraint(
            model_name="dispatchoperation",
            name="saas_dispatch_unknown_time",
        ),
        migrations.RemoveConstraint(
            model_name="jobattempt",
            name="saas_attempt_status",
        ),
        migrations.RemoveConstraint(
            model_name="joboutbox",
            name="saas_outbox_status",
        ),
        migrations.AlterField(
            model_name="dispatchoperation",
            name="status",
            field=models.CharField(default="started", max_length=8),
        ),
        migrations.AddConstraint(
            model_name="dispatchoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["started", "unknown", "success", "noeffect"])),
                name="saas_dispatch_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="dispatchoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "started"), ("unknown_at__isnull", True)),
                    models.Q(("status", "unknown"), ("unknown_at__isnull", False)),
                    ("status__in", ["success", "noeffect"]),
                    _connector="OR",
                ),
                name="saas_dispatch_unknown_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["leased", "expired", "cancelled", "started", "done"])
                ),
                name="saas_attempt_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="joboutbox",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["pending", "cancelled", "started", "done"])),
                name="saas_outbox_status",
            ),
        ),
        migrations.AddField(
            model_name="dispatchreceipt",
            name="operation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="core.dispatchoperation"
            ),
        ),
        migrations.AddConstraint(
            model_name="dispatchreceipt",
            constraint=models.UniqueConstraint(
                fields=("source_code", "receipt_ref"), name="saas_receipt_ref"
            ),
        ),
        migrations.AddConstraint(
            model_name="dispatchreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(("outcome__in", ["success", "noeffect"])),
                name="saas_receipt_outcome",
            ),
        ),
        migrations.AddConstraint(
            model_name="dispatchreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("outcome", "noeffect"), ("provider_calls", 0)),
                    models.Q(("outcome", "success"), ("provider_calls__gte", 1)),
                    _connector="OR",
                ),
                name="saas_receipt_effect_calls",
            ),
        ),
        migrations.AddField(
            model_name="dispatchoperation",
            name="call_limit",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(migrations.RunPython.noop, protect_receipt_rollback),
    ]
