# Generated by Django 5.2.18 on 2026-10-07 23:06

import uuid

import django.db.models.deletion
from django.db import migrations, models


def protect_period_rollback(apps, schema_editor):
    if apps.get_model("core", "UsagePeriod").objects.using(schema_editor.connection.alias).exists():
        raise RuntimeError(
            "Period accounting history exists; destructive rollback requires an explicit migration plan."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_terminal_receipts"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsagePeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.CharField(max_length=128)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("status", models.CharField(default="open", max_length=6)),
                ("settled_snapshot", models.JSONField(null=True)),
                ("closed_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.workspace"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="usagecounter",
            name="period",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="core.usageperiod"
            ),
        ),
        migrations.AddField(
            model_name="usagereservation",
            name="period",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="core.usageperiod"
            ),
        ),
        migrations.AddConstraint(
            model_name="usageperiod",
            constraint=models.UniqueConstraint(fields=("workspace", "key"), name="saas_period_key"),
        ),
        migrations.AddConstraint(
            model_name="usageperiod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("workspace",),
                name="saas_one_open_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="usageperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_at__gt", models.F("starts_at"))), name="saas_period_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="usageperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("closed_at__isnull", True),
                        ("settled_snapshot__isnull", True),
                        ("status", "open"),
                    ),
                    models.Q(
                        ("closed_at__isnull", False),
                        ("settled_snapshot__isnull", False),
                        ("status", "closed"),
                    ),
                    _connector="OR",
                ),
                name="saas_period_close_evidence",
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, protect_period_rollback),
    ]
