# Generated by Django 5.2.18 on 2026-10-07 23:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def protect_schedule_rollback(apps, schema_editor):
    if (
        apps.get_model("core", "DailySchedule")
        .objects.using(schema_editor.connection.alias)
        .exists()
    ):
        raise RuntimeError("Schedule history exists; rollback needs an explicit preservation plan.")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_usage_periods"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.CharField(max_length=128)),
                ("timezone", models.CharField(max_length=64)),
                ("local_time", models.TimeField()),
                ("search", models.JSONField()),
                ("request_hash", models.CharField(max_length=64)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.workspace"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleOccurrence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("schedule_revision", models.PositiveIntegerField()),
                ("local_date", models.DateField()),
                ("local_time", models.TimeField()),
                ("timezone", models.CharField(max_length=64)),
                ("request_hash", models.CharField(max_length=64)),
                ("scheduled_for", models.DateTimeField(null=True)),
                ("utc_offset_seconds", models.IntegerField(null=True)),
                ("resolution", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.OneToOneField(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="core.job"
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.dailyschedule"
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.workspace"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="dailyschedule",
            constraint=models.UniqueConstraint(
                fields=("workspace", "key"), name="saas_schedule_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="saas_schedule_revision"
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleoccurrence",
            constraint=models.UniqueConstraint(
                fields=("schedule", "local_date"), name="saas_daily_occurrence"
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("job__isnull", True),
                        ("resolution", "skipped_day"),
                        ("scheduled_for__isnull", True),
                        ("utc_offset_seconds__isnull", True),
                    ),
                    models.Q(
                        ("job__isnull", False),
                        ("resolution__in", ["normal", "gap_forward", "ambiguous_earlier"]),
                        ("scheduled_for__isnull", False),
                        ("utc_offset_seconds__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="saas_occurrence_decision",
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, protect_schedule_rollback),
    ]
