# Generated by Django 5.2.18 on 2026-10-08 11:27

import django.db.models.deletion
from django.db import migrations, models


def protect_candidate_rollback(apps, schema_editor):
    if (
        apps.get_model("core", "CandidateEvidence")
        .objects.using(schema_editor.connection.alias)
        .exists()
    ):
        raise RuntimeError(
            "Candidate evidence exists; rollback needs an explicit preservation plan."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_daily_occurrences"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_code", models.CharField(max_length=64)),
                ("event_ref", models.CharField(max_length=96)),
                ("body_hash", models.CharField(max_length=64)),
                ("candidate_count", models.PositiveIntegerField()),
                ("earliest_delete_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="core.dispatchoperation"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_code", "event_ref"), name="saas_candidate_event"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("candidate_count__gte", 1), ("candidate_count__lte", 25)
                        ),
                        name="saas_candidate_count",
                    ),
                ],
            },
        ),
        migrations.RunPython(migrations.RunPython.noop, protect_candidate_rollback),
    ]
