# Generated by Django 5.2.18 on 2026-10-08 12:41

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def protect_export_rollback(apps, schema_editor):
    if (
        apps.get_model("core", "ResultExport")
        .objects.using(schema_editor.connection.alias)
        .exists()
    ):
        raise RuntimeError("Export accounting exists; rollback requires a preservation plan.")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_accepted_results"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.CharField(max_length=128)),
                ("request_hash", models.CharField(max_length=64)),
                ("content_digest", models.CharField(max_length=64)),
                ("record_count", models.PositiveIntegerField()),
                ("delete_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.job"),
                ),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="core.usagereservation"
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.workspace"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("workspace", "key"), name="saas_export_key"),
                    models.CheckConstraint(
                        condition=models.Q(("record_count__gte", 1), ("record_count__lte", 25)),
                        name="saas_export_count",
                    ),
                ],
            },
        ),
        migrations.RunPython(migrations.RunPython.noop, protect_export_rollback),
    ]
