# Generated by Django 5.2.18 on 2026-10-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_result_erasure"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="resultexport",
            index=models.Index(
                fields=["workspace", "job", "-created_at", "-id"], name="saas_export_job_history"
            ),
        ),
        migrations.AddIndex(
            model_name="resultexport",
            index=models.Index(
                fields=["workspace", "job", "created_by", "-created_at", "-id"],
                name="saas_export_actor_history",
            ),
        ),
    ]
