# Generated by Django 5.2.18 on 2026-10-08 16:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def protect_billing_rollback(apps, schema_editor):
    alias = schema_editor.connection.alias
    if (
        apps.get_model("core", "BillingAccount").objects.using(alias).exists()
        or apps.get_model("core", "BillingEvent").objects.using(alias).exists()
        or apps.get_model("core", "Entitlement")
        .objects.using(alias)
        .filter(valid_until__isnull=False)
        .exists()
    ):
        raise RuntimeError("Billing evidence exists; rollback requires a preservation plan.")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_export_history_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="entitlement",
            name="valid_until",
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name="BillingAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("issuer_code", models.CharField(max_length=64)),
                ("enabled", models.BooleanField(default=False)),
                ("revision", models.PositiveIntegerField(default=0)),
                ("issued_at", models.DateTimeField(null=True)),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="core.workspace"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="entitlement",
            name="billing_account",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="core.billingaccount"
            ),
        ),
        migrations.CreateModel(
            name="BillingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("issuer_code", models.CharField(max_length=64)),
                ("event_ref", models.CharField(max_length=96)),
                ("revision", models.PositiveIntegerField()),
                ("body_hash", models.CharField(max_length=64)),
                ("key_id", models.CharField(max_length=64)),
                ("issued_at", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("active", models.BooleanField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.billingaccount"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.workspace"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("issuer_code", "event_ref"), name="saas_billing_event"
                    ),
                    models.UniqueConstraint(
                        fields=("account", "revision"), name="saas_billing_revision"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("revision__gte", 1)), name="saas_billing_positive"
                    ),
                ],
            },
        ),
        migrations.RunPython(migrations.RunPython.noop, protect_billing_rollback),
    ]
