# Generated by Django 5.2.18 on 2026-10-08 17:19

import uuid

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


def protect_batch_rollback(apps, schema_editor):
    alias = schema_editor.connection.alias
    for name in ("ResultBatch", "BatchCandidateEvidence", "BatchAcceptance", "SourceBatchTerminal"):
        if apps.get_model("core", name).objects.using(alias).exists():
            raise RuntimeError("V3 batch evidence exists; rollback requires a preservation plan.")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_billing_reconciliation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("ordinal", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="core.dispatchoperation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BatchCandidateEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_code", models.CharField(max_length=64)),
                ("event_ref", models.CharField(max_length=96)),
                ("body_hash", models.CharField(max_length=64)),
                ("candidate_count", models.PositiveIntegerField()),
                ("earliest_delete_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="core.resultbatch"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceBatchTerminal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_code", models.CharField(max_length=64)),
                ("receipt_ref", models.CharField(max_length=96)),
                ("source_key_id", models.CharField(max_length=64)),
                ("body_hash", models.CharField(max_length=64)),
                ("batch_set_hash", models.CharField(max_length=64)),
                ("batch_count", models.PositiveIntegerField()),
                ("accepted_count", models.PositiveIntegerField()),
                ("provider_calls", models.PositiveIntegerField()),
                ("issued_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="core.dispatchoperation"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BatchAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_code", models.CharField(max_length=64)),
                ("receipt_ref", models.CharField(max_length=96)),
                ("source_key_id", models.CharField(max_length=64)),
                ("dedupe_key_id", models.CharField(max_length=64)),
                ("body_hash", models.CharField(max_length=64)),
                ("namespace", models.CharField(max_length=96)),
                ("accepted_count", models.PositiveIntegerField()),
                ("provider_calls", models.PositiveIntegerField()),
                ("issued_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.batchcandidateevidence",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_code", "receipt_ref"), name="saas_batch_accept_ref"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("accepted_count__gte", 1), ("accepted_count__lte", 25)),
                        name="saas_batch_accepted_count",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("provider_calls__gte", 1)), name="saas_batch_calls"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="resultbatch",
            constraint=models.UniqueConstraint(
                fields=("operation", "ordinal"), name="saas_batch_ordinal"
            ),
        ),
        migrations.AddConstraint(
            model_name="resultbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("ordinal__gte", 1)), name="saas_batch_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="batchcandidateevidence",
            constraint=models.UniqueConstraint(
                fields=("source_code", "event_ref"), name="saas_batch_candidate_ref"
            ),
        ),
        migrations.AddConstraint(
            model_name="batchcandidateevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(("candidate_count__gte", 1), ("candidate_count__lte", 25)),
                name="saas_batch_candidate_count",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcebatchterminal",
            constraint=models.UniqueConstraint(
                fields=("source_code", "receipt_ref"), name="saas_batch_terminal_ref"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcebatchterminal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("accepted_count", 0), ("batch_count", 0)),
                    models.Q(
                        ("accepted_count__gte", models.F("batch_count")),
                        (
                            "accepted_count__lte",
                            django.db.models.expressions.CombinedExpression(
                                models.Value(25), "*", models.F("batch_count")
                            ),
                        ),
                        ("batch_count__gte", 1),
                        ("provider_calls__gte", 1),
                    ),
                    _connector="OR",
                ),
                name="saas_batch_terminal_counts",
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, protect_batch_rollback),
    ]
