# Generated by Django 5.2.18 on 2026-10-08 18:02

from django.db import migrations, models


def protect_protocol_rollback(apps, schema_editor):
    if (
        apps.get_model("core", "JobOutbox")
        .objects.using(schema_editor.connection.alias)
        .filter(result_protocol=3)
        .exists()
    ):
        raise RuntimeError("V3 enrollment exists; rollback requires a preservation plan.")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_batch_evidence_scaffold"),
    ]

    operations = [
        migrations.AddField(
            model_name="joboutbox",
            name="result_protocol",
            field=models.PositiveSmallIntegerField(default=2, editable=False),
        ),
        migrations.AddConstraint(
            model_name="joboutbox",
            constraint=models.CheckConstraint(
                condition=models.Q(("result_protocol__in", [2, 3])), name="saas_outbox_protocol"
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, protect_protocol_rollback),
    ]
