# Generated by Django 5.2.18 on 2026-10-08 18:37

import django.db.models.deletion
from django.db import migrations, models


def protect_payload_rollback(apps, schema_editor):
    if (
        apps.get_model("core", "AcceptedResult")
        .objects.using(schema_editor.connection.alias)
        .filter(batch_acceptance__isnull=False)
        .exists()
    ):
        raise RuntimeError(
            "V3 accepted payload or tombstones exist; rollback requires a preservation plan."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_batch_protocol_selection"),
    ]

    operations = [
        migrations.AddField(
            model_name="acceptedresult",
            name="batch_acceptance",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="core.batchacceptance"
            ),
        ),
        migrations.AddField(
            model_name="acceptedresult",
            name="batch_position",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="acceptedresult",
            name="acceptance",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="core.resultacceptance"
            ),
        ),
        migrations.AddConstraint(
            model_name="acceptedresult",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("acceptance__isnull", False),
                        ("batch_acceptance__isnull", True),
                        ("batch_position__isnull", True),
                    ),
                    models.Q(
                        ("acceptance__isnull", True),
                        ("batch_acceptance__isnull", False),
                        ("batch_position__gte", 1),
                        ("batch_position__isnull", False),
                        ("batch_position__lte", 25),
                    ),
                    _connector="OR",
                ),
                name="saas_result_protocol_link",
            ),
        ),
        migrations.AddConstraint(
            model_name="acceptedresult",
            constraint=models.UniqueConstraint(
                fields=("batch_acceptance", "record_ref"), name="saas_batch_result_ref"
            ),
        ),
        migrations.AddConstraint(
            model_name="acceptedresult",
            constraint=models.UniqueConstraint(
                fields=("batch_acceptance", "batch_position"), name="saas_batch_result_position"
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, protect_payload_rollback),
    ]
