-- VSN Lead Engine compact scalable Registry schema blueprint.
-- Apply to a dedicated Supabase project only after project/cost approval.
-- Full lead data remains in dated Google Sheets. The DB stores only compact
-- dedupe fingerprints and minimum transaction-recovery metadata.

create table if not exists public.vsn_lead_registry (
    id bigint generated by default as identity primary key,
    first_added date not null,
    category text not null,
    country_code char(2) not null,
    unique_token text not null,
    fingerprints text[] not null check (cardinality(fingerprints) > 0),
    daily_sheet_id text not null default '',
    status text not null default 'PendingDaily'
        check (status in ('PendingDaily','Active','Retryable')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- Exact reservation identity. Non-blocking Retryable rows can be replaced later.
create unique index if not exists vsn_lead_registry_unique_token_uq
    on public.vsn_lead_registry (unique_token)
    where status in ('Active','PendingDaily');

-- One compact overlap index replaces six separate raw-value indexes.
create index if not exists vsn_lead_registry_fingerprints_gin
    on public.vsn_lead_registry using gin (fingerprints)
    where status in ('Active','PendingDaily');

create index if not exists vsn_lead_registry_status_idx
    on public.vsn_lead_registry (status);

create index if not exists vsn_lead_registry_first_added_idx
    on public.vsn_lead_registry (first_added desc);

alter table public.vsn_lead_registry enable row level security;

revoke all on table public.vsn_lead_registry from public, anon, authenticated;
grant select, insert, update on table public.vsn_lead_registry to service_role;
grant usage, select on sequence public.vsn_lead_registry_id_seq to service_role;

create or replace function public.vsn_lead_registry_collisions(p_rows jsonb)
returns table(candidate_unique_token text)
language sql
security invoker
set search_path = public
as $$
    with incoming as (
        select
            lower(trim(x.candidate_unique_token)) as candidate_unique_token,
            x.fingerprints
        from jsonb_to_recordset(coalesce(p_rows, '[]'::jsonb)) as x(
            candidate_unique_token text,
            fingerprints text[]
        )
        where nullif(trim(x.candidate_unique_token), '') is not null
          and cardinality(x.fingerprints) > 0
    )
    select distinct i.candidate_unique_token
    from incoming i
    where exists (
        select 1
        from public.vsn_lead_registry r
        where r.status in ('Active','PendingDaily')
          and r.fingerprints && i.fingerprints
    );
$$;

create or replace function public.vsn_lead_registry_reserve(p_rows jsonb)
returns table(unique_token text)
language plpgsql
security invoker
set search_path = public
as $$
declare
    item record;
    inserted_token text;
begin
    -- Serialize reservations so two concurrent workers cannot reserve
    -- different rows that share a secondary fingerprint.
    perform pg_advisory_xact_lock(86120001);

    for item in
        select *
        from jsonb_to_recordset(coalesce(p_rows, '[]'::jsonb)) as x(
            first_added text,
            category text,
            country_code text,
            unique_token text,
            fingerprints text[],
            daily_sheet_id text,
            status text
        )
    loop
        item.unique_token := lower(trim(coalesce(item.unique_token, '')));
        if item.unique_token = '' or cardinality(item.fingerprints) is null then
            continue;
        end if;

        if exists (
            select 1
            from public.vsn_lead_registry r
            where r.status in ('Active','PendingDaily')
              and r.fingerprints && item.fingerprints
        ) then
            continue;
        end if;

        begin
            insert into public.vsn_lead_registry (
                first_added, category, country_code, unique_token,
                fingerprints, daily_sheet_id, status
            )
            values (
                item.first_added::date,
                item.category,
                upper(left(item.country_code, 2)),
                item.unique_token,
                item.fingerprints,
                coalesce(item.daily_sheet_id, ''),
                'PendingDaily'
            )
            returning public.vsn_lead_registry.unique_token into inserted_token;

            unique_token := inserted_token;
            return next;
        exception when unique_violation then
            null;
        end;
    end loop;
end;
$$;

create or replace function public.vsn_lead_registry_activate(p_tokens text[])
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
    changed bigint;
begin
    update public.vsn_lead_registry
       set status = 'Active', updated_at = now()
     where unique_token = any(p_tokens)
       and status = 'PendingDaily';
    get diagnostics changed = row_count;
    return changed;
end;
$$;

create or replace function public.vsn_lead_registry_mark_retryable(p_tokens text[])
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
    changed bigint;
begin
    update public.vsn_lead_registry
       set status = 'Retryable', updated_at = now()
     where unique_token = any(p_tokens)
       and status = 'PendingDaily';
    get diagnostics changed = row_count;
    return changed;
end;
$$;

create or replace function public.vsn_lead_registry_pending()
returns table(unique_token text, category text, daily_sheet_id text)
language sql
security invoker
set search_path = public
as $$
    select r.unique_token, r.category, r.daily_sheet_id
    from public.vsn_lead_registry r
    where r.status = 'PendingDaily'
    order by r.id
    limit 5000;
$$;

create or replace function public.vsn_lead_registry_import(p_rows jsonb)
returns table(unique_token text)
language plpgsql
security invoker
set search_path = public
as $$
declare
    item record;
    inserted_token text;
begin
    perform pg_advisory_xact_lock(86120001);

    for item in
        select *
        from jsonb_to_recordset(coalesce(p_rows, '[]'::jsonb)) as x(
            first_added text,
            category text,
            country_code text,
            unique_token text,
            fingerprints text[],
            daily_sheet_id text,
            status text
        )
    loop
        item.unique_token := lower(trim(coalesce(item.unique_token, '')));
        if item.unique_token = '' or cardinality(item.fingerprints) is null then
            continue;
        end if;

        if exists (
            select 1
            from public.vsn_lead_registry r
            where r.status in ('Active','PendingDaily')
              and r.fingerprints && item.fingerprints
        ) then
            continue;
        end if;

        begin
            insert into public.vsn_lead_registry (
                first_added, category, country_code, unique_token,
                fingerprints, daily_sheet_id, status
            )
            values (
                item.first_added::date,
                item.category,
                upper(left(item.country_code, 2)),
                item.unique_token,
                item.fingerprints,
                coalesce(item.daily_sheet_id, ''),
                case when item.status = 'PendingDaily'
                    then 'PendingDaily' else 'Active' end
            )
            returning public.vsn_lead_registry.unique_token into inserted_token;

            unique_token := inserted_token;
            return next;
        exception when unique_violation then
            null;
        end;
    end loop;
end;
$$;

create or replace function public.vsn_lead_registry_stats()
returns table(
    total_rows bigint,
    blocking_rows bigint,
    pending_rows bigint,
    table_bytes bigint,
    index_bytes bigint,
    total_bytes bigint,
    database_bytes bigint
)
language sql
security invoker
set search_path = public
as $$
    select
        count(*)::bigint as total_rows,
        count(*) filter (where status in ('Active','PendingDaily'))::bigint as blocking_rows,
        count(*) filter (where status = 'PendingDaily')::bigint as pending_rows,
        pg_relation_size('public.vsn_lead_registry')::bigint as table_bytes,
        pg_indexes_size('public.vsn_lead_registry')::bigint as index_bytes,
        pg_total_relation_size('public.vsn_lead_registry')::bigint as total_bytes,
        pg_database_size(current_database())::bigint as database_bytes
    from public.vsn_lead_registry;
$$;

revoke execute on function public.vsn_lead_registry_collisions(jsonb) from public, anon, authenticated;
revoke execute on function public.vsn_lead_registry_reserve(jsonb) from public, anon, authenticated;
revoke execute on function public.vsn_lead_registry_activate(text[]) from public, anon, authenticated;
revoke execute on function public.vsn_lead_registry_mark_retryable(text[]) from public, anon, authenticated;
revoke execute on function public.vsn_lead_registry_pending() from public, anon, authenticated;
revoke execute on function public.vsn_lead_registry_import(jsonb) from public, anon, authenticated;
revoke execute on function public.vsn_lead_registry_stats() from public, anon, authenticated;

grant execute on function public.vsn_lead_registry_collisions(jsonb) to service_role;
grant execute on function public.vsn_lead_registry_reserve(jsonb) to service_role;
grant execute on function public.vsn_lead_registry_activate(text[]) to service_role;
grant execute on function public.vsn_lead_registry_mark_retryable(text[]) to service_role;
grant execute on function public.vsn_lead_registry_pending() to service_role;
grant execute on function public.vsn_lead_registry_import(jsonb) to service_role;
grant execute on function public.vsn_lead_registry_stats() to service_role;
