-- VSN Lead Engine scalable Registry schema blueprint.
-- Apply to a dedicated Supabase project after project selection.
-- This file is intentionally not a Supabase migration-history file yet.

create table if not exists public.vsn_lead_registry (
    id bigint generated by default as identity primary key,
    first_added date not null,
    category text not null,
    country text not null,
    city text not null default '',
    business_name text not null,
    website text not null default '',
    normalized_domain text,
    phone text not null,
    normalized_phone text not null,
    phone_name_key text,
    business_location_key text,
    unique_key text not null,
    daily_sheet text not null default '',
    daily_sheet_url text not null default '',
    status text not null default 'PendingDaily'
        check (status in ('PendingDaily','Active','NeedsReview','Retryable','Rejected','Invalid','Quarantined')),
    region text not null default '',
    postal_code text not null default '',
    google_place_id text,
    source text not null default '',
    source_id text,
    verification_sources text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists vsn_lead_registry_unique_key_uq
    on public.vsn_lead_registry (unique_key)
    where status in ('Active','PendingDaily');
create unique index if not exists vsn_lead_registry_domain_uq
    on public.vsn_lead_registry (normalized_domain)
    where normalized_domain is not null and normalized_domain <> ''
      and status in ('Active','PendingDaily');
create unique index if not exists vsn_lead_registry_phone_name_uq
    on public.vsn_lead_registry (phone_name_key)
    where phone_name_key is not null and phone_name_key <> ''
      and status in ('Active','PendingDaily');
create unique index if not exists vsn_lead_registry_business_location_uq
    on public.vsn_lead_registry (business_location_key)
    where business_location_key is not null and business_location_key <> ''
      and status in ('Active','PendingDaily');
create unique index if not exists vsn_lead_registry_place_id_uq
    on public.vsn_lead_registry (google_place_id)
    where google_place_id is not null and google_place_id <> ''
      and status in ('Active','PendingDaily');
create unique index if not exists vsn_lead_registry_source_id_uq
    on public.vsn_lead_registry (source_id)
    where source_id is not null and source_id <> ''
      and status in ('Active','PendingDaily');
create index if not exists vsn_lead_registry_status_idx
    on public.vsn_lead_registry (status);
create index if not exists vsn_lead_registry_first_added_idx
    on public.vsn_lead_registry (first_added desc);

alter table public.vsn_lead_registry enable row level security;

revoke all on table public.vsn_lead_registry from public, anon, authenticated;
grant select, insert, update on table public.vsn_lead_registry to service_role;
grant usage, select on sequence public.vsn_lead_registry_id_seq to service_role;

create or replace function public.vsn_lead_registry_collisions(p_rows jsonb)
returns table(candidate_unique_key text)
language sql
security invoker
set search_path = public
as $$
    with incoming as (
        select
            nullif(lower(trim(x.candidate_unique_key)), '') as candidate_unique_key,
            nullif(lower(trim(x.google_place_id)), '') as google_place_id,
            nullif(lower(trim(x.source_id)), '') as source_id,
            nullif(lower(trim(x.normalized_domain)), '') as normalized_domain,
            nullif(lower(trim(x.phone_name_key)), '') as phone_name_key,
            nullif(lower(trim(x.business_location_key)), '') as business_location_key
        from jsonb_to_recordset(coalesce(p_rows, '[]'::jsonb)) as x(
            candidate_unique_key text,
            google_place_id text,
            source_id text,
            normalized_domain text,
            phone_name_key text,
            business_location_key text
        )
    )
    select distinct i.candidate_unique_key
    from incoming i
    join public.vsn_lead_registry r
      on lower(r.status) in ('active','pendingdaily')
     and (
          (i.candidate_unique_key is not null and lower(r.unique_key) = i.candidate_unique_key)
       or (i.google_place_id is not null and lower(r.google_place_id) = i.google_place_id)
       or (i.source_id is not null and lower(r.source_id) = i.source_id)
       or (i.normalized_domain is not null and lower(r.normalized_domain) = i.normalized_domain)
       or (i.phone_name_key is not null and lower(r.phone_name_key) = i.phone_name_key)
       or (i.business_location_key is not null and lower(r.business_location_key) = i.business_location_key)
     )
    where i.candidate_unique_key is not null;
$$;

create or replace function public.vsn_lead_registry_reserve(p_rows jsonb)
returns table(unique_key text)
language sql
security invoker
set search_path = public
as $$
    insert into public.vsn_lead_registry (
        first_added, category, country, city, business_name, website,
        normalized_domain, phone, normalized_phone, phone_name_key,
        business_location_key, unique_key, daily_sheet, daily_sheet_url,
        status, region, postal_code, google_place_id, source, source_id,
        verification_sources
    )
    select
        x.first_added::date,
        x.category,
        x.country,
        coalesce(x.city, ''),
        x.business_name,
        coalesce(x.website, ''),
        nullif(lower(trim(x.normalized_domain)), ''),
        x.phone,
        x.normalized_phone,
        nullif(lower(trim(x.phone_name_key)), ''),
        nullif(lower(trim(x.business_location_key)), ''),
        lower(x.unique_key),
        coalesce(x.daily_sheet, ''),
        coalesce(x.daily_sheet_url, ''),
        'PendingDaily',
        coalesce(x.region, ''),
        coalesce(x.postal_code, ''),
        nullif(lower(trim(x.google_place_id)), ''),
        coalesce(x.source, ''),
        nullif(lower(trim(x.source_id)), ''),
        coalesce(x.verification_sources, '')
    from jsonb_to_recordset(coalesce(p_rows, '[]'::jsonb)) as x(
        first_added text,
        category text,
        country text,
        city text,
        business_name text,
        website text,
        normalized_domain text,
        phone text,
        normalized_phone text,
        phone_name_key text,
        business_location_key text,
        unique_key text,
        daily_sheet text,
        daily_sheet_url text,
        status text,
        region text,
        postal_code text,
        google_place_id text,
        source text,
        source_id text,
        verification_sources text
    )
    on conflict do nothing
    returning public.vsn_lead_registry.unique_key;
$$;

create or replace function public.vsn_lead_registry_activate(p_keys text[])
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
    changed bigint;
begin
    update public.vsn_lead_registry
       set status = 'Active', updated_at = now()
     where unique_key = any(p_keys)
       and status = 'PendingDaily';
    get diagnostics changed = row_count;
    return changed;
end;
$$;

create or replace function public.vsn_lead_registry_mark_retryable(p_keys text[])
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
    changed bigint;
begin
    update public.vsn_lead_registry
       set status = 'Retryable', updated_at = now()
     where unique_key = any(p_keys)
       and status = 'PendingDaily';
    get diagnostics changed = row_count;
    return changed;
end;
$$;

create or replace function public.vsn_lead_registry_pending()
returns table(unique_key text, category text, daily_sheet_url text)
language sql
security invoker
set search_path = public
as $
    select r.unique_key, r.category, r.daily_sheet_url
      from public.vsn_lead_registry r
     where r.status = 'PendingDaily'
     order by r.id
     limit 5000;
$;

create or replace function public.vsn_lead_registry_import(p_rows jsonb)
returns table(unique_key text)
language sql
security invoker
set search_path = public
as $
    insert into public.vsn_lead_registry (
        first_added, category, country, city, business_name, website,
        normalized_domain, phone, normalized_phone, phone_name_key,
        business_location_key, unique_key, daily_sheet, daily_sheet_url,
        status, region, postal_code, google_place_id, source, source_id,
        verification_sources
    )
    select
        x.first_added::date,
        x.category,
        x.country,
        coalesce(x.city, ''),
        x.business_name,
        coalesce(x.website, ''),
        nullif(lower(trim(x.normalized_domain)), ''),
        x.phone,
        x.normalized_phone,
        nullif(lower(trim(x.phone_name_key)), ''),
        nullif(lower(trim(x.business_location_key)), ''),
        lower(x.unique_key),
        coalesce(x.daily_sheet, ''),
        coalesce(x.daily_sheet_url, ''),
        case
            when x.status in ('PendingDaily','Active','NeedsReview','Retryable','Rejected','Invalid','Quarantined')
                then x.status
            else 'Active'
        end,
        coalesce(x.region, ''),
        coalesce(x.postal_code, ''),
        nullif(lower(trim(x.google_place_id)), ''),
        coalesce(x.source, ''),
        nullif(lower(trim(x.source_id)), ''),
        coalesce(x.verification_sources, '')
    from jsonb_to_recordset(coalesce(p_rows, '[]'::jsonb)) as x(
        first_added text,
        category text,
        country text,
        city text,
        business_name text,
        website text,
        normalized_domain text,
        phone text,
        normalized_phone text,
        phone_name_key text,
        business_location_key text,
        unique_key text,
        daily_sheet text,
        daily_sheet_url text,
        status text,
        region text,
        postal_code text,
        google_place_id text,
        source text,
        source_id text,
        verification_sources text
    )
    on conflict do nothing
    returning public.vsn_lead_registry.unique_key;
$;

revoke execute on function public.vsn_lead_registry_collisions(jsonb) from public, anon, authenticated;
revoke execute on function public.vsn_lead_registry_reserve(jsonb) from public, anon, authenticated;
revoke execute on function public.vsn_lead_registry_activate(text[]) from public, anon, authenticated;
revoke execute on function public.vsn_lead_registry_mark_retryable(text[]) from public, anon, authenticated;
revoke execute on function public.vsn_lead_registry_pending() from public, anon, authenticated;
revoke execute on function public.vsn_lead_registry_import(jsonb) from public, anon, authenticated;

grant execute on function public.vsn_lead_registry_collisions(jsonb) to service_role;
grant execute on function public.vsn_lead_registry_reserve(jsonb) to service_role;
grant execute on function public.vsn_lead_registry_activate(text[]) to service_role;
grant execute on function public.vsn_lead_registry_mark_retryable(text[]) to service_role;
grant execute on function public.vsn_lead_registry_pending() to service_role;
grant execute on function public.vsn_lead_registry_import(jsonb) to service_role;
