from __future__ import annotations

import argparse
import difflib
import json
import platform
import pip
import re
import subprocess
import sys
import tempfile
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


ROOT=Path(__file__).resolve().parents[1]
PYPROJECT=ROOT/"pyproject.toml"
BOOTSTRAP=ROOT/"requirements-bootstrap.txt"
RUNTIME=ROOT/"requirements-runtime.txt"
DEV=ROOT/"requirements-dev.txt"
RESOLVER=ROOT/".github/dependency-resolver.txt"

LOCK_LINE_RE=re.compile(
    r"^(?P<name>[A-Za-z0-9_.-]+)==(?P<version>[^\s]+)"
    r"(?: --hash=sha256:(?P<hash>[0-9a-f]{64}))?$"
)
EXACT_REQ_RE=re.compile(
    r"^(?P<name>[A-Za-z0-9_.-]+)==(?P<version>[^\s;]+)$"
)


@dataclass(frozen=True,order=True)
class ResolvedArtifact:
    name: str
    version: str
    sha256: str


def normalize_name(name: str) -> str:
    return re.sub(r"[-_.]+","-",name).lower()


def ensure_platform() -> None:
    if sys.version_info[:2] != (3,12):
        raise SystemExit(
            f"Hash-lock regeneration requires CPython 3.12; got {platform.python_version()}."
        )
    if not sys.platform.startswith("linux"):
        raise SystemExit(
            f"Hash-lock regeneration requires Linux; got {sys.platform}."
        )


def read_pyproject() -> dict:
    return tomllib.loads(PYPROJECT.read_text(encoding="utf-8"))


def ensure_resolver() -> None:
    versions=parse_existing_versions(RESOLVER)
    expected=versions.get("pip")
    if not expected:
        raise SystemExit(".github/dependency-resolver.txt must pin pip exactly.")
    if pip.__version__ != expected:
        raise SystemExit(
            "Hash-lock regeneration requires the reviewed pip resolver "
            f"{expected}; got {pip.__version__}. Install it with "
            "'python -m pip install --require-hashes "
            "-r .github/dependency-resolver.txt'."
        )


def parse_existing_versions(path: Path) -> dict[str,str]:
    result={}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line=raw.strip()
        if not line or line.startswith("#") or line.startswith("-r "):
            continue
        match=LOCK_LINE_RE.fullmatch(line)
        if not match:
            raise SystemExit(f"Unparseable lock line in {path.name}: {line}")
        name=normalize_name(match.group("name"))
        if name in result:
            raise SystemExit(f"Duplicate lock entry in {path.name}: {name}")
        result[name]=match.group("version")
    return result


def exact_build_requirements(data: dict) -> list[str]:
    requirements=list(data["build-system"]["requires"])
    for requirement in requirements:
        if not EXACT_REQ_RE.fullmatch(requirement):
            raise SystemExit(
                "Build requirements must stay exact-pinned before hash regeneration: "
                f"{requirement}"
            )
    return requirements


def run_resolver(requirements: Iterable[str], report_path: Path) -> None:
    command=[
        sys.executable,
        "-m",
        "pip",
        "install",
        "--disable-pip-version-check",
        "--no-input",
        "--dry-run",
        "--ignore-installed",
        "--report",
        str(report_path),
        *requirements,
    ]
    subprocess.run(command,cwd=ROOT,check=True)


def artifacts_from_report(path: Path) -> dict[str,ResolvedArtifact]:
    data=json.loads(path.read_text(encoding="utf-8"))
    result={}
    for item in data.get("install",[]):
        metadata=item.get("metadata") or {}
        raw_name=str(metadata.get("name") or "").strip()
        version=str(metadata.get("version") or "").strip()
        if not raw_name or not version:
            raise SystemExit(f"Resolver report missing package identity: {path}")
        name=normalize_name(raw_name)

        archive=(item.get("download_info") or {}).get("archive_info") or {}
        hashes=archive.get("hashes") or {}
        sha256=str(hashes.get("sha256") or "").strip()
        if not sha256:
            legacy=str(archive.get("hash") or "")
            if legacy.startswith("sha256="):
                sha256=legacy.split("=",1)[1]
        if not re.fullmatch(r"[0-9a-f]{64}",sha256):
            raise SystemExit(f"Resolver report missing SHA-256 for {name}=={version}")

        artifact=ResolvedArtifact(name=name,version=version,sha256=sha256)
        previous=result.get(name)
        if previous is not None and previous != artifact:
            raise SystemExit(f"Resolver produced conflicting artifacts for {name}")
        result[name]=artifact
    return result


def format_rows(rows: Iterable[ResolvedArtifact]) -> list[str]:
    return [
        f"{row.name}=={row.version} --hash=sha256:{row.sha256}"
        for row in sorted(rows)
    ]


def render_bootstrap(rows: dict[str,ResolvedArtifact]) -> str:
    lines=[
        "# VSN Lead Engine hash-verified installer/build bootstrap",
        "# Generated by scripts/regenerate_hash_locks.py on Linux / CPython 3.12.",
        "# Review dependency-version changes before merging regenerated hashes.",
        *format_rows(rows.values()),
    ]
    return "\n".join(lines)+"\n"


def render_runtime(rows: dict[str,ResolvedArtifact]) -> str:
    lines=[
        "# VSN Lead Engine hash-verified runtime lock",
        "# Platform: GitHub-hosted Ubuntu / CPython 3.12",
        "# Generated by scripts/regenerate_hash_locks.py from pyproject.toml.",
        "# Review dependency-version changes before merging regenerated hashes.",
        *format_rows(rows.values()),
    ]
    return "\n".join(lines)+"\n"


def render_dev(
    runtime: dict[str,ResolvedArtifact],
    dev: dict[str,ResolvedArtifact],
) -> str:
    for name,runtime_artifact in runtime.items():
        dev_artifact=dev.get(name)
        if dev_artifact != runtime_artifact:
            raise SystemExit(
                "Development resolution changed a runtime artifact; "
                f"cannot compose -r requirements-runtime.txt safely: {name}"
            )
    delta={name:item for name,item in dev.items() if name not in runtime}
    lines=[
        "# VSN Lead Engine hash-verified development lock",
        "# Generated by scripts/regenerate_hash_locks.py; includes runtime plus test-only dependencies.",
        "-r requirements-runtime.txt",
        *format_rows(delta.values()),
    ]
    return "\n".join(lines)+"\n"


def generate_contents() -> dict[Path,str]:
    ensure_platform()
    ensure_resolver()
    data=read_pyproject()
    project=data["project"]
    runtime_requirements=list(project["dependencies"])
    dev_requirements=[
        *runtime_requirements,
        *project.get("optional-dependencies",{}).get("dev",[]),
    ]

    bootstrap_requirements=exact_build_requirements(data)

    with tempfile.TemporaryDirectory(prefix="vsn-lock-") as tmp:
        temp=Path(tmp)
        bootstrap_report=temp/"bootstrap.json"
        runtime_report=temp/"runtime.json"
        dev_report=temp/"dev.json"

        run_resolver(bootstrap_requirements,bootstrap_report)
        run_resolver(runtime_requirements,runtime_report)
        run_resolver(dev_requirements,dev_report)

        bootstrap_rows=artifacts_from_report(bootstrap_report)
        runtime_rows=artifacts_from_report(runtime_report)
        dev_rows=artifacts_from_report(dev_report)

    return {
        BOOTSTRAP:render_bootstrap(bootstrap_rows),
        RUNTIME:render_runtime(runtime_rows),
        DEV:render_dev(runtime_rows,dev_rows),
    }


def diff_for(path: Path,expected: str) -> str:
    current=path.read_text(encoding="utf-8") if path.exists() else ""
    return "".join(
        difflib.unified_diff(
            current.splitlines(keepends=True),
            expected.splitlines(keepends=True),
            fromfile=str(path.relative_to(ROOT)),
            tofile=f"{path.relative_to(ROOT)} (regenerated)",
        )
    )


def write_contents(contents: dict[Path,str]) -> bool:
    changed=False
    for path,expected in contents.items():
        current=path.read_text(encoding="utf-8") if path.exists() else ""
        if current == expected:
            continue
        path.write_text(expected,encoding="utf-8")
        changed=True
        print(f"updated {path.relative_to(ROOT)}")
    return changed


def check_contents(contents: dict[Path,str]) -> bool:
    diffs=[]
    for path,expected in contents.items():
        diff=diff_for(path,expected)
        if diff:
            diffs.append(diff)
    if diffs:
        print(
            "Dependency hash locks are stale. Run "
            "'python scripts/regenerate_hash_locks.py --write' on Linux / CPython 3.12."
        )
        print("\n".join(diffs))
        return False
    print("Dependency hash locks match a fresh resolver result.")
    return True


def main() -> int:
    parser=argparse.ArgumentParser(
        description="Regenerate or verify VSN hash-locked Python dependencies."
    )
    mode=parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write",action="store_true")
    mode.add_argument("--check",action="store_true")
    args=parser.parse_args()

    contents=generate_contents()
    if args.write:
        write_contents(contents)
        return 0
    return 0 if check_contents(contents) else 1


if __name__ == "__main__":
    raise SystemExit(main())
